---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: purelb
  name: allocator
  namespace: purelb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: purelb
  name: lbnodeagent
  namespace: purelb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: purelb
  name: purelb:allocator
rules:
- apiGroups:
  - purelb.io
  resources:
  - servicegroups
  - lbnodeagents
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - update
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - policy
  resourceNames:
  - allocator
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: purelb
  name: purelb:lbnodeagent
rules:
- apiGroups:
  - purelb.io
  resources:
  - servicegroups
  - lbnodeagents
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - endpoints
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - policy
  resourceNames:
  - lbnodeagent
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: purelb
  name: pod-lister
  namespace: purelb
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: purelb
  name: purelb:allocator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purelb:allocator
subjects:
- kind: ServiceAccount
  name: allocator
  namespace: purelb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: purelb
  name: purelb:lbnodeagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purelb:lbnodeagent
subjects:
- kind: ServiceAccount
  name: lbnodeagent
  namespace: purelb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: purelb
  name: pod-lister
  namespace: purelb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-lister
subjects:
- kind: ServiceAccount
  name: lbnodeagent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: purelb
    component: lbnodeagent
  name: lbnodeagent
  namespace: purelb
spec:
  selector:
    matchLabels:
      app: purelb
      component: lbnodeagent
  template:
    metadata:
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
      labels:
        app: purelb
        component: lbnodeagent
    spec:
      containers:
      - env:
        - name: NETBOX_USER_TOKEN
          valueFrom:
            secretKeyRef:
              name: netbox-client
              key: user-token
              optional: true
        - name: PURELB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PURELB_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PURELB_ML_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ML_GROUP
          value: 8sb7ikA5qHwQQqxc
        image: registry.gitlab.com/purelb/purelb/lbnodeagent:main-latest
        imagePullPolicy: Always
        name: lbnodeagent
        ports:
        - containerPort: 7472
          name: monitoring
        resources:
          limits:
            memory: 100Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          readOnlyRootFilesystem: true
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: lbnodeagent
      terminationGracePeriodSeconds: 2
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: purelb
    component: allocator
  name: allocator
  namespace: purelb
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: purelb
      component: allocator
  template:
    metadata:
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
      labels:
        app: purelb
        component: allocator
    spec:
      containers:
      - image: registry.gitlab.com/purelb/purelb/allocator:main-latest
        env:
        - name: NETBOX_USER_TOKEN
          valueFrom:
            secretKeyRef:
              name: netbox-client
              key: user-token
              optional: true
        - name: DEFAULT_ANNOUNCER
          value: "PureLB"
        imagePullPolicy: Always
        name: allocator
        ports:
        - containerPort: 7472
          name: monitoring
        resources:
          limits:
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: allocator
      terminationGracePeriodSeconds: 0
